services:
  - type: worker
    name: darkhorses-statistics-worker
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python3 update_stats.py --loop
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: LOG_LEVEL
        value: INFO
      - key: PYTHONUNBUFFERED
        value: 1
