# Consolidated ONE Service Architecture
# Runs API + All Schedulers in ONE process for $7/month (not $21/month)

services:
  - type: web
    name: darkhorses-racing-odds
    env: python
    rootDir: api
    plan: starter  # Requires always-on for background scheduler
    buildCommand: pip install -r requirements.txt
    startCommand: python3 start.py
    envVars:
      - key: RACING_API_USERNAME
        sync: false
      - key: RACING_API_PASSWORD
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: LOG_LEVEL
        value: INFO
      - key: PORT
        value: 8000
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PYTHONDONTWRITEBYTECODE
        value: 1
    healthCheckPath: /health
