services:
  # Odds Workers - Live odds, historical odds, and statistics
  - type: web
    name: darkhorses-odds-workers
    env: python
    plan: starter  # Required for always-on (not free tier)
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python3 start_workers.py
    envVars:
      - key: RACING_API_USERNAME
        sync: false
      - key: RACING_API_PASSWORD
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: LOG_LEVEL
        value: INFO
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PYTHONDONTWRITEBYTECODE
        value: 1
