# DarkHorses Backend - Workers Only
# Background data collection service (no API)

services:
  # Background Workers - Data Collection Service
  - type: web
    name: darkhorses-workers
    env: python
    plan: starter  # Requires always-on for continuous data collection
    rootDir: workers
    buildCommand: pip install -r requirements.txt
    startCommand: python3 start_workers.py
    envVars:
      - key: RACING_API_USERNAME
        sync: false
      - key: RACING_API_PASSWORD
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: LOG_LEVEL
        value: INFO
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PYTHONDONTWRITEBYTECODE
        value: 1
