services:
  # Consolidated Workers - All data collection in one service
  - type: web
    name: darkhorses-workers
    env: python
    plan: starter  # Required for always-on (not free tier)
    runtime: python-3.12
    buildCommand: pip install -r requirements.txt
    startCommand: python3 start_workers.py
    envVars:
      - key: RACING_API_USERNAME
        sync: false
      - key: RACING_API_PASSWORD
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: LOG_LEVEL
        value: INFO
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PYTHONDONTWRITEBYTECODE
        value: 1
