services:
  - type: web
    name: racing-api-masters-api
    env: python
    region: oregon
    plan: starter
    buildCommand: pip install -r requirements-api.txt
    startCommand: uvicorn api_service:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.6
      - key: DATABASE_URL
        sync: false
    healthCheckPath: /health
