services:
  - type: worker
    name: darkhorses-historical-odds-worker
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python3 cron_historical.py
    envVars:
      - key: RACING_API_USERNAME
        sync: false
      - key: RACING_API_PASSWORD
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: LOG_LEVEL
        value: INFO
      - key: PYTHONUNBUFFERED
        value: 1
